### PR TITLE
Update main.js and io-package.json with DC-1-3 Informations

### PR DESCRIPTION
**Pull request by tobstare**
Added DC1-3 Informations for Current, Voltage and Power. (Testet with Piko15)

### CODE REVIEW

**Comment by hombach** [comment]
package.json must have same version string - will be fixed after merge

**Comment by hombach** [comment]
const ID_Power_DC3Current             = 33555713;  // in A
const ID_Power_DC3Voltage             = 33555714;  // in V
const ID_Power_DC3Power               = 33555715;  // in W
should only work with PIKO Systems... we will see how PIKO BA will react on this.
YOu tested with PIKO 15 .... without battery... looks like you had no issues with request for battery data

**Comment by tobstare** [comment]
Yes, it worked well with my Piko 15 without a battery.

**Comment by hombach** [comment]
Works also with Piko BA with battery - DC 3 data is equal to battery data
FYI: I changed DC current values to mA accuracy in version 1.1.1

**Pull request merged**
